# Generated by Django 5.1.6 on 2025-03-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
