# Generated by Django 5.1.6 on 2025-03-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_questionbank_record_formresponse_school_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormResponse',
        ),
    ]
