# Generated by Django 5.1.6 on 2025-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_formresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_teacher',
            name='school_name',
        ),
        migrations.AddField(
            model_name='school_teacher',
            name='schools',
            field=models.ManyToManyField(to='app.school'),
        ),
    ]
