# Generated by Django 5.1.6 on 2025-03-10 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_school_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_teacher',
            name='schools',
        ),
        migrations.AddField(
            model_name='school_teacher',
            name='school_name',
            field=models.CharField(default='Unknown School', max_length=100),
        ),
        migrations.AlterField(
            model_name='school_teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
